// Generated by EmDash & typed for PrivateSector collections
/// <reference types="emdash/locals" />

import type { BylineSummary, ContentBylineCredit, TaxonomyTerm, PortableTextBlock } from "emdash";

declare module 'sanitize-html';

export interface EmDashImage {
  id: string;
  src?: string;
  alt?: string;
  width?: number;
  height?: number;
  filename?: string;
  mimeType?: string;
  blurhash?: string;
  dominantColor?: string;
  focalX?: number;
  focalY?: number;
  provider?: string;
  previewUrl?: string;
  meta?: Record<string, unknown>;
}

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  subtitle?: string;
  featured_image?: EmDashImage;
  content?: PortableTextBlock[];
  excerpt?: string;
  pull_quote?: string;
  read_time_mins?: number;
  author_name?: string;
  author_avatar?: string;
  student_author_id?: number;
  focus_keyword?: string;
  meta_title?: string;
  meta_description?: string;
  schema_markup?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Blog {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  subtitle?: string;
  featured_image?: EmDashImage;
  content?: PortableTextBlock[];
  excerpt?: string;
  pull_quote?: string;
  read_time_mins?: number;
  author_name?: string;
  author_avatar?: string;
  focus_keyword?: string;
  meta_title?: string;
  meta_description?: string;
  schema_markup?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Company {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  logo_bg?: string;
  canton?: string;
  industry?: string;
  size_class?: string;
  description?: string;
  premium?: boolean;
  verified?: boolean;
  founded?: number;
  employees?: number;
  revenue_band?: string;
  website?: string;
  linkedin?: string;
  contact_email?: string;
  about_text?: string;
  structured_data?: string;
  esg_rating?: number;
  sustainability_summary?: string;
  meta_title?: string;
  meta_description?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Interview {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  subtitle?: string;
  interviewee_name?: string;
  interviewee_title?: string;
  interviewee_avatar?: string;
  company_name?: string;
  audio_url?: string;
  read_time_mins?: number;
  qa_content?: string;
  student_author_id?: number;
  category?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Briefing {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  date?: string;
  audio_url?: string;
  audio_duration?: number;
  transcript?: string;
  featured_image?: EmDashImage;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
}

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    posts: Post;
    blogs: Blog;
    companies: Company;
    interviews: Interview;
    briefings: Briefing;
    pages: Page;
  }
}